# Generated by Django 4.2.7 on 2024-09-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
