# Generated by Django 4.2.7 on 2024-09-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
